$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths: ['dist', 'node_modules']
words:
  - afonso
  - angelov
  - apna
  - araujo
  - arra
  - astro
  - astrojs
  - autoplay
  - bhavesh
  - bigl
  - bryanoltman
  - cancelbots
  - codemagic
  - codelessly
  - copplestone
  - chromecast
  - cupertino
  - devnomic
  - dominik
  - dougall
  - dreamflow
  - droidcon
  - eseidel
  - esra
  - evenodd
  - felangel
  - felangelov
  - findstr
  - fintech
  - fluttercon
  - flutterconusa
  - fontsource
  - fouc
  - footguns
  - frontends
  - frontmatter
  - gallego
  - ghisi
  - grayscale
  - hackathon
  - headshot
  - headshots
  - howzat
  - icaza
  - idris
  - itar
  - jsxs
  - junglee
  - kadah
  - kalshi
  - kellar
  - kijiji
  - killop
  - klub
  - lavamoat
  - leeming
  - logcat
  - macdougall
  - mailchimp
  - mairramer
  - miklas
  - narkhede
  - neha
  - nowrap
  - nubank
  - nowa
  - oltman
  - onclick
  - pageload
  - palo
  - parzych
  - pichai
  - posthog
  - pubspec
  - pushpress
  - renan
  - roadmaps
  - rollout
  - rollouts
  - roszkowski
  - sagalov
  - seidel
  - shorebirddev
  - shorebirdtech
  - siclen
  - signup
  - signups
  - solana
  - solides
  - souza
  - sundar
  - sunsetting
  - snopes
  - stac
  - squircle
  - squircles
  - superlist
  - taha
  - techlead
  - tesser
  - thiago
  - tomarra
  - tradeling
  - transformative
  - tsconfigs
  - umit
  - underperforming
  - unsexy
  - upson
  - upvoted
  - userbase
  - veloso
  - vyuh
  - wagus
  - widgetbook
  - wolt
  - xlink
