$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths: ['dist', 'node_modules']
words:
  - BIGL
  - FOUC
  - ITAR
  - angelov
  - araujo
  - astro
  - astrojs
  - cancelbots
  - codemagic
  - eseidel
  - findstr
  - fontsource
  - frontmatter
  - headshot
  - jsxs
  - junglee
  - kijiji
  - logcat
  - mailchimp
  - oltman
  - pubspec
  - renan
  - seidel
  - signups
  - superlist
  - taha
  - tesser
  - tsconfigs
  - upvoted
  - xlink
