$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths: ['dist', 'node_modules']
words:
  - angelov
  - apna
  - araujo
  - astro
  - astrojs
  - BIGL
  - bryanoltman
  - cancelbots
  - codemagic
  - devnomic
  - eseidel
  - felangel
  - findstr
  - fontsource
  - FOUC
  - frontmatter
  - headshot
  - ITAR
  - jsxs
  - junglee
  - kalshi
  - kijiji
  - klub
  - logcat
  - mailchimp
  - oltman
  - onclick
  - Palo
  - pubspec
  - renan
  - rollout
  - rollouts
  - seidel
  - shorebirdtech
  - signups
  - superlist
  - taha
  - tesser
  - tradeling
  - tsconfigs
  - upvoted
  - userbase
  - xlink
