$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths: ['dist', 'node_modules']
words:
  - angelov
  - apna
  - araujo
  - arra
  - astro
  - astrojs
  - autoplay
  - bhavesh
  - BIGL
  - bryanoltman
  - cancelbots
  - codemagic
  - devnomic
  - dougall
  - dominik
  - eseidel
  - esra
  - evenodd
  - felangel
  - felangelov
  - findstr
  - fintech
  - fontsource
  - FOUC
  - frontmatter
  - ghisi
  - grayscale
  - headshot
  - headshots
  - howzat
  - ITAR
  - jsxs
  - junglee
  - kalshi
  - kadah
  - kijiji
  - klub
  - leeming
  - logcat
  - macdougall
  - mailchimp
  - nubank
  - oltman
  - onclick
  - Palo
  - pubspec
  - renan
  - rollout
  - rollouts
  - roszkowski
  - seidel
  - shorebirddev
  - shorebirdtech
  - signups
  - superlist
  - taha
  - tesser
  - thiago
  - tomarra
  - tradeling
  - tsconfigs
  - upvoted
  - userbase
  - xlink
