version: '3'

volumes:
  node_modules:

services:
  shorebird-site:
    build: .
    container_name: shorebird-site
    stdin_open: true
    tty: true
    ports:
      - 4321:4321
      - 35729:35729
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
